@startuml
!pragma teoz true
skinparam SequenceMessageAlign direction
title Sell order flow
actor Browser <<User>> order 1
participant BFF order 2
entity Portfolio <<PersistentEntity>> order 3
collections OrderPlaced  <<Topic>> order 4
collections OrderResult <<Topic>> order 5
entity Broker <<PersistentEntity>> order 6
box "Portfolio Service"
  participant Portfolio
  participant OrderPlaced
end box
box "Broker Service"
  participant Broker
  participant OrderResult
end box
Browser -> BFF: sell shares
activate BFF
BFF -> Portfolio: placeOrder
activate Portfolio
Portfolio --> Portfolio : confirm and\nremove shares
Portfolio -> OrderPlaced: OrderPlaced
& Portfolio -> BFF: <OrderId>
deactivate Portfolio
activate OrderPlaced #blue
OrderPlaced -[#blue]->> Broker: OrderPlaced
activate Broker
deactivate OrderPlaced
BFF -> Browser: OK
deactivate BFF
Broker --> Broker: Find buyer
Broker -> OrderResult: Fulfilled
activate OrderResult #blue
deactivate Broker
OrderResult -[#blue]->> Portfolio: Fulfilled
& OrderResult -[#blue]->> BFF: Fulfilled
activate BFF
activate Portfolio
deactivate OrderResult
BFF -> Browser: order update
& Portfolio --> Portfolio: Credit funds
deactivate Portfolio
deactivate BFF
@enduml