@startuml
!pragma teoz true

[*] --> TransferInitiated : TransferFunds
note left of TransferInitiated
  Request funds from source account
end note
TransferInitiated --> UnableToSecureFunds : RequestFailed
TransferInitiated --> FundsSent : RequestSucceeded
note left of FundsSent
  Send funds to destination
end note
FundsSent --> DeliveryConfirmed : DeliverySuccessful
FundsSent --> RefundSent : DeliveryFailed
note left of RefundSent
  Send refund to source
end note
RefundSent --> RefundSent : RefundFailed
RefundSent --> RefundDelivered : RefundSucceeded

@enduml